use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;

/// Convert configuration from system.prop format to config.toml
pub fn convert_config(input: &str, output: &str) -> Result<()> {
    println!("Converting config from {} to {}", input, output);

    let content = fs::read_to_string(input).context("Failed to read input file")?;
    let mut properties = HashMap::new();

    // Process each line manually instead of using regex
    for line in content.lines() {
        // Skip comments and empty lines
        let trimmed_line = line.trim();
        if trimmed_line.is_empty() || trimmed_line.starts_with('#') {
            continue;
        }

        // Find the first equals sign
        if let Some(equals_pos) = trimmed_line.find('=') {
            let key = trimmed_line[..equals_pos].trim();
            let value = trimmed_line[equals_pos + 1..].trim();

            if !key.is_empty() && !value.is_empty() {
                properties.insert(key.to_string(), value.to_string());
            }
        }
    }

    // Determine template name
    // Priority: marketname > model > name > "generated_template"
    let template_name = properties
        .get("ro.product.marketname")
        .or_else(|| properties.get("ro.product.model"))
        .or_else(|| properties.get("ro.product.name"))
        .or_else(|| properties.get("ro.product.device"))
        .cloned()
        .unwrap_or_else(|| "generated_template".to_string());

    let mut toml_output = String::new();
    toml_output.push_str("# Generated by device_faker_cli\n");
    // Use quoted key for template name to handle spaces safely
    toml_output.push_str(&format!("[templates.\"{}\"]\n", template_name));
    toml_output.push_str("packages = []\n");

    if let Some(val) = properties.get("ro.product.manufacturer") {
        toml_output.push_str(&format!("manufacturer = \"{}\"\n", val));
    }
    if let Some(val) = properties.get("ro.product.brand") {
        toml_output.push_str(&format!("brand = \"{}\"\n", val));
    }
    if let Some(val) = properties.get("ro.product.model") {
        toml_output.push_str(&format!("model = \"{}\"\n", val));
    }
    if let Some(val) = properties.get("ro.build.fingerprint") {
        toml_output.push_str(&format!("fingerprint = \"{}\"\n", val));
    }

    // name maps to ro.product.name OR ro.product.device
    if let Some(val) = properties.get("ro.product.name") {
        toml_output.push_str(&format!("name = \"{}\"\n", val));
    } else if let Some(val) = properties.get("ro.product.device") {
        toml_output.push_str(&format!("name = \"{}\"\n", val));
    }

    if let Some(val) = properties.get("ro.product.marketname") {
        toml_output.push_str(&format!("marketname = \"{}\"\n", val));
    }

    fs::write(output, toml_output).context("Failed to write output file")?;
    println!("Conversion complete.");

    Ok(())
}
